"""
Field Catalog — defines all supported data fields, their sources,
World Bank indicators, IMF codes, and search templates.
"""
from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class FieldDefinition:
    field_name: str
    display_name: str
    preferred_source: str
    fallback_sources: List[str]
    requires_api_key: bool
    api_key_service: Optional[str]
    search_query_template: str
    unit: str
    category: str
    world_bank_indicator: Optional[str] = None
    imf_code: Optional[str] = None
    oecd_dataset: Optional[str] = None
    description: str = ""


FIELD_CATALOG: Dict[str, FieldDefinition] = {
    # ── Economic ──────────────────────────────────────────────
    "gdp_usd": FieldDefinition(
        field_name="gdp_usd",
        display_name="GDP (USD)",
        preferred_source="world_bank",
        fallback_sources=["imf", "web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} GDP total US dollars {year}",
        unit="USD",
        category="economic",
        world_bank_indicator="NY.GDP.MKTP.CD",
        imf_code="NGDPD",
        description="Gross Domestic Product in current USD",
    ),
    "gdp_per_capita": FieldDefinition(
        field_name="gdp_per_capita",
        display_name="GDP per Capita (USD)",
        preferred_source="world_bank",
        fallback_sources=["imf", "web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} GDP per capita current US dollars {year}",
        unit="USD",
        category="economic",
        world_bank_indicator="NY.GDP.PCAP.CD",
        imf_code="NGDPDPC",
        description="GDP per capita in current USD",
    ),
    "gdp_growth_rate": FieldDefinition(
        field_name="gdp_growth_rate",
        display_name="GDP Growth Rate (%)",
        preferred_source="world_bank",
        fallback_sources=["imf", "web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} GDP growth rate annual percent {year}",
        unit="%",
        category="economic",
        world_bank_indicator="NY.GDP.MKTP.KD.ZG",
        imf_code="NGDP_RPCH",
        description="Annual GDP growth rate as percentage",
    ),
    "inflation_rate": FieldDefinition(
        field_name="inflation_rate",
        display_name="Inflation Rate (%)",
        preferred_source="world_bank",
        fallback_sources=["imf", "web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} inflation rate consumer prices annual percent {year}",
        unit="%",
        category="economic",
        world_bank_indicator="FP.CPI.TOTL.ZG",
        imf_code="PCPIPCH",
        description="Consumer price inflation (annual %)",
    ),
    "unemployment_rate": FieldDefinition(
        field_name="unemployment_rate",
        display_name="Unemployment Rate (%)",
        preferred_source="world_bank",
        fallback_sources=["imf", "web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} unemployment rate percent total {year}",
        unit="%",
        category="economic",
        world_bank_indicator="SL.UEM.TOTL.ZS",
        imf_code="LUR",
        description="Unemployment as % of total labor force",
    ),
    "current_account_balance_pct_gdp": FieldDefinition(
        field_name="current_account_balance_pct_gdp",
        display_name="Current Account Balance (% GDP)",
        preferred_source="imf",
        fallback_sources=["world_bank", "web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} current account balance percent GDP {year}",
        unit="% GDP",
        category="economic",
        world_bank_indicator="BN.CAB.XOKA.GD.ZS",
        imf_code="BCA_NGDPD",
        description="Current account balance as % of GDP",
    ),
    "government_debt_pct_gdp": FieldDefinition(
        field_name="government_debt_pct_gdp",
        display_name="Government Debt (% GDP)",
        preferred_source="imf",
        fallback_sources=["world_bank", "web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} government gross debt percent GDP {year}",
        unit="% GDP",
        category="economic",
        imf_code="GGXWDG_NGDP",
        description="General government gross debt as % of GDP",
    ),
    "trade_balance_usd": FieldDefinition(
        field_name="trade_balance_usd",
        display_name="Trade Balance (USD)",
        preferred_source="world_bank",
        fallback_sources=["web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} trade balance exports minus imports USD {year}",
        unit="USD",
        category="economic",
        world_bank_indicator="NE.RSB.GNFS.CD",
        description="Trade balance (exports minus imports) in USD",
    ),
    "fdi_inflows_usd": FieldDefinition(
        field_name="fdi_inflows_usd",
        display_name="FDI Inflows (USD)",
        preferred_source="world_bank",
        fallback_sources=["web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} foreign direct investment inflows USD {year}",
        unit="USD",
        category="economic",
        world_bank_indicator="BX.KLT.DINV.CD.WD",
        description="Foreign direct investment inflows in USD",
    ),
    "exchange_rate_usd": FieldDefinition(
        field_name="exchange_rate_usd",
        display_name="Exchange Rate (per USD)",
        preferred_source="world_bank",
        fallback_sources=["alpha_vantage", "web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} official exchange rate LCU per USD {year}",
        unit="LCU/USD",
        category="economic",
        world_bank_indicator="PA.NUS.FCRF",
        description="Official exchange rate (local currency per USD)",
    ),
    # ── Demographic ───────────────────────────────────────────
    "population": FieldDefinition(
        field_name="population",
        display_name="Population",
        preferred_source="world_bank",
        fallback_sources=["rest_countries", "web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} total population {year}",
        unit="persons",
        category="demographic",
        world_bank_indicator="SP.POP.TOTL",
        description="Total population",
    ),
    "population_growth_rate": FieldDefinition(
        field_name="population_growth_rate",
        display_name="Population Growth Rate (%)",
        preferred_source="world_bank",
        fallback_sources=["web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} population growth rate annual percent {year}",
        unit="%",
        category="demographic",
        world_bank_indicator="SP.POP.GROW",
        description="Annual population growth rate",
    ),
    "life_expectancy": FieldDefinition(
        field_name="life_expectancy",
        display_name="Life Expectancy (years)",
        preferred_source="world_bank",
        fallback_sources=["web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} life expectancy at birth total years {year}",
        unit="years",
        category="demographic",
        world_bank_indicator="SP.DYN.LE00.IN",
        description="Life expectancy at birth (years)",
    ),
    "literacy_rate": FieldDefinition(
        field_name="literacy_rate",
        display_name="Literacy Rate (%)",
        preferred_source="world_bank",
        fallback_sources=["web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} adult literacy rate percent {year}",
        unit="%",
        category="demographic",
        world_bank_indicator="SE.ADT.LITR.ZS",
        description="Adult literacy rate (% of people ages 15+)",
    ),
    "hdi_index": FieldDefinition(
        field_name="hdi_index",
        display_name="Human Development Index",
        preferred_source="world_bank",
        fallback_sources=["web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} human development index HDI score {year}",
        unit="index (0-1)",
        category="demographic",
        description="Human Development Index (0–1 scale)",
    ),
    "urbanization_rate": FieldDefinition(
        field_name="urbanization_rate",
        display_name="Urbanization Rate (%)",
        preferred_source="world_bank",
        fallback_sources=["web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} urban population percent total {year}",
        unit="%",
        category="demographic",
        world_bank_indicator="SP.URB.TOTL.IN.ZS",
        description="Urban population as % of total population",
    ),
    # ── Climate / Environment ─────────────────────────────────
    "co2_emissions_per_capita": FieldDefinition(
        field_name="co2_emissions_per_capita",
        display_name="CO₂ Emissions per Capita (tonnes)",
        preferred_source="world_bank",
        fallback_sources=["web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} CO2 emissions per capita metric tons {year}",
        unit="tonnes/capita",
        category="climate",
        world_bank_indicator="EN.ATM.CO2E.PC",
        description="CO₂ emissions per capita in metric tonnes",
    ),
    "temperature_anomaly": FieldDefinition(
        field_name="temperature_anomaly",
        display_name="Temperature Anomaly (°C)",
        preferred_source="open_meteo",
        fallback_sources=["web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} average annual temperature {year}",
        unit="°C",
        category="climate",
        description="Average annual temperature (°C)",
    ),
    "renewable_energy_share": FieldDefinition(
        field_name="renewable_energy_share",
        display_name="Renewable Energy Share (%)",
        preferred_source="world_bank",
        fallback_sources=["web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} renewable energy percentage total electricity {year}",
        unit="%",
        category="climate",
        world_bank_indicator="EG.ELC.RNEW.ZS",
        description="Renewable electricity output as % of total",
    ),
    # ── Political / Governance ────────────────────────────────
    "political_stability_index": FieldDefinition(
        field_name="political_stability_index",
        display_name="Political Stability Index",
        preferred_source="world_bank",
        fallback_sources=["web_search"],
        requires_api_key=False,
        api_key_service=None,
        search_query_template="{entity} political stability absence violence World Bank governance indicator {year}",
        unit="index (-2.5 to 2.5)",
        category="governance",
        world_bank_indicator="PV.EST",
        description="World Bank Political Stability & Absence of Violence index",
    ),
    # ── Financial (requires API key) ──────────────────────────
    "stock_index_level": FieldDefinition(
        field_name="stock_index_level",
        display_name="Stock Index Level",
        preferred_source="alpha_vantage",
        fallback_sources=["web_search"],
        requires_api_key=True,
        api_key_service="alpha_vantage",
        search_query_template="{entity} stock market index level {year}",
        unit="index points",
        category="financial",
        description="National stock market index level (year-end)",
    ),
    # ── News / Sentiment (requires API key) ───────────────────
    "news_sentiment_score": FieldDefinition(
        field_name="news_sentiment_score",
        display_name="News Volume",
        preferred_source="newsapi",
        fallback_sources=["web_search"],
        requires_api_key=True,
        api_key_service="newsapi",
        search_query_template="{entity} news articles count {year}",
        unit="article count",
        category="news",
        description="Number of news articles mentioning this entity",
    ),
}
